src/fr/azerks/model/User.java
package fr.azerks.model;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;

public class User {

    private String name;
    private String password;
    private Boolean isLogged = false;
    public HashSet<Product> cart;

    public User(String name, String password, HashSet<Product> cart) {
        this.name = name;
        this.password = password;
        this.cart = cart;
    }

    public void addProduct(Product product){
         cart.add(product);
    }

    public HashSet<Product> getProducts(String username, String password, HashSet<Product> cart) {
        return cart;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Boolean isLogged() {
        return isLogged;
    }

    public void setLogged(Boolean log) {
        isLogged = log;
    }

    @Override
    public String toString() {
        return "User{" +
                "name='" + name + '\'' +
                ", password='" + password + '\'' +
                ", cart='" + cart + '\'' +
                '}';
    }
    public double getTotal() {
        double total = 0;
        for (Product entry : cart) {
            total += entry.getPrice() * entry.getQuantity();
        }
        return total;
    }

}

web/index.jsp
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Project</title>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
</head>
<body>

<div>
    <h1>Menu</h1>
</div>

<div>
    <div>
        <button onclick="location.href='/list'">List users</button>
        <button onclick="location.href='/add'">Add user</button>
        <button onclick="location.href='/remove'">Remove user</button>
        <button onclick="location.href='/connection'">Connection user</button>
    </div>
    <div>
        <c:if test="${sessionScope.logged == true}">
            <button onclick="location.href='/shop'">Shop</button>
            <button onclick="location.href='/cart'">Your Cart</button>
        </c:if>
    </div>
</div>
</body>
</html>